--- 
deployment: 
  tasks: 
    - export DEPLOYPATH=/home/mattzunw/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - export DEPLOYPATHIMAGES=/home/mattzunw/public_html/images/
    - /bin/cp -R Images $DEPLOYPATHIMAGES