---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mattzunw/public_html/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R docs $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R index.html $DEPLOYPATH