---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mattzunw/public_html/
    - /bin/cp -R images $DEPLOYPATHimages
    - /bin/cp -R docs $DEPLOYPATHdocs
    - /bin/cp -R css $DEPLOYPATHcss
    - /bin/cp index.html $DEPLOYPATH